version: "3.8"

services:
  node1:
    image: besu-image-local:2.0
    container_name: node1.2
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,TRACE,DEBUG,TXPOOL,PERM
      --rpc-ws-enabled=true
      --rpc-ws-port=8645
      --rpc-http-port=8545
      --metrics-enabled
      --metrics-port=9545
      --p2p-port=30303
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --data-storage-format=BONSAI
      --tx-pool-min-gas-price=0
      --min-gas-price=0
      --tx-pool-limit-by-account-percentage=1
      --tx-pool-max-size=4096
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-1/data:/opt/besu/data

  node2:
    image: besu-image-local:2.0
    container_name: node2.2
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://36e645d7aa6df3dcafec97b01d075bdfb49433471eef9a3e3172b55711a419edc089325e3b4a999ba16f830070d18f8c51418c65f583ae0928519ea8ee55033c@192.168.0.9:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,TRACE,DEBUG,TXPOOL,PERM
      --rpc-ws-enabled=true
      --rpc-ws-port=8646
      --rpc-http-port=8546
      --metrics-enabled
      --metrics-port=9546
      --p2p-port=30304
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --data-storage-format=BONSAI
      --tx-pool-min-gas-price=0
      --min-gas-price=0
      --tx-pool-limit-by-account-percentage=1
      --tx-pool-max-size=4096
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-2/data:/opt/besu/data

  node3:
    image: besu-image-local:2.0
    container_name: node3.2
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://36e645d7aa6df3dcafec97b01d075bdfb49433471eef9a3e3172b55711a419edc089325e3b4a999ba16f830070d18f8c51418c65f583ae0928519ea8ee55033c@192.168.0.9:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,TRACE,DEBUG,TXPOOL,PERM
      --rpc-ws-enabled=true
      --rpc-ws-port=8647
      --rpc-http-port=8547
      --metrics-enabled
      --metrics-port=9547
      --p2p-port=30305
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --data-storage-format=BONSAI
      --tx-pool-min-gas-price=0
      --min-gas-price=0
      --tx-pool-limit-by-account-percentage=1
      --tx-pool-max-size=4096
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-3/data:/opt/besu/data

  node4:
    image: besu-image-local:2.0
    container_name: node4.2
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://36e645d7aa6df3dcafec97b01d075bdfb49433471eef9a3e3172b55711a419edc089325e3b4a999ba16f830070d18f8c51418c65f583ae0928519ea8ee55033c@192.168.0.9:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,TRACE,DEBUG,TXPOOL,PERM
      --rpc-ws-enabled=true
      --rpc-ws-port=8648
      --rpc-http-port=8548
      --metrics-enabled
      --metrics-port=9548
      --p2p-port=30306
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --data-storage-format=BONSAI
      --tx-pool-min-gas-price=0
      --min-gas-price=0
      --tx-pool-limit-by-account-percentage=1
      --tx-pool-max-size=4096
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-4/data:/opt/besu/data

  node5:
    image: besu-image-local:2.0
    container_name: node5.2
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://36e645d7aa6df3dcafec97b01d075bdfb49433471eef9a3e3172b55711a419edc089325e3b4a999ba16f830070d18f8c51418c65f583ae0928519ea8ee55033c@192.168.0.9:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,TRACE,DEBUG,TXPOOL,PERM
      --rpc-ws-enabled=true
      --rpc-ws-port=8649
      --rpc-http-port=8549
      --metrics-enabled
      --metrics-port=9549
      --p2p-port=30307
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --data-storage-format=BONSAI
      --tx-pool-min-gas-price=0
      --min-gas-price=0
      --tx-pool-limit-by-account-percentage=1
      --tx-pool-max-size=4096
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-5/data:/opt/besu/data

  node6:
    image: besu-image-local:2.0
    container_name: node6.2
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://36e645d7aa6df3dcafec97b01d075bdfb49433471eef9a3e3172b55711a419edc089325e3b4a999ba16f830070d18f8c51418c65f583ae0928519ea8ee55033c@192.168.0.9:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,TRACE,DEBUG,TXPOOL,PERM
      --rpc-ws-enabled=true
      --rpc-ws-port=8650
      --rpc-http-port=8550
      --metrics-enabled
      --metrics-port=9550
      --p2p-port=30308
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --data-storage-format=BONSAI
      --tx-pool-min-gas-price=0
      --min-gas-price=0
      --tx-pool-limit-by-account-percentage=1
      --tx-pool-max-size=4096
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-6/data:/opt/besu/data

networks:
  default:
    name: besu-network
    external: true